"""Expense table created

Revision ID: d968228a055a
Revises: d7bd66dc96b4
Create Date: 2026-08-13 08:52:53.871720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd968228a055a'
down_revision: Union[str, Sequence[str], None] = 'd7bd66dc96b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_name', sa.String(), nullable=False),
    sa.Column('expense_description', sa.String(), nullable=True),
    sa.Column('expense_category', postgresql.ENUM('OTHERS', 'FOOD', 'GROCERY', 'TRIP', 'STUDY', name='expense_category'), nullable=False),
    sa.Column('expense_amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
